/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author dam
 */
public class Operaciones extends javax.swing.JFrame {

    /**
     * Creates new form Operaciones
     */
    public Operaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuOperraciones = new javax.swing.JMenu();
        MenuItemAltaClientes = new javax.swing.JMenuItem();
        MenuItemManteRutinas = new javax.swing.JMenuItem();
        MenuItemHistorial = new javax.swing.JMenuItem();
        MenuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuOperraciones.setText("Operaciones");

        MenuItemAltaClientes.setText("Alta Clientes");
        MenuItemAltaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAltaClientesActionPerformed(evt);
            }
        });
        MenuOperraciones.add(MenuItemAltaClientes);

        MenuItemManteRutinas.setText("Mantenimiento Rutinas");
        MenuItemManteRutinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemManteRutinasActionPerformed(evt);
            }
        });
        MenuOperraciones.add(MenuItemManteRutinas);

        MenuItemHistorial.setText("Historial Entrenamiento");
        MenuItemHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemHistorialActionPerformed(evt);
            }
        });
        MenuOperraciones.add(MenuItemHistorial);

        jMenuBar1.add(MenuOperraciones);

        MenuSalir.setText("Salir");
        jMenuBar1.add(MenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemAltaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAltaClientesActionPerformed
                                                         
        
        pnAltaClientes panelAlta = new pnAltaClientes();
        
        //  Uso setBounds para  las dimensiones y posición exacta
        // Tomamos el ancho y alto actual del JFrame (la ventana principal)
        panelAlta.setBounds(0, 0, this.getWidth(), this.getHeight());
        
        //  el panel sea visible
        panelAlta.setVisible(true);
        
        // quitamos cualquier panel que estuviera ante)
        this.getContentPane().removeAll();
        
        //  layout simple que ocupa toda la pantalla
        this.getContentPane().setLayout(new java.awt.BorderLayout());
        
        //  Añadir el panel de Alta de Clientes en el centro
        this.getContentPane().add(panelAlta, java.awt.BorderLayout.CENTER);
        
        //  Refrescamos toda la jerarquía de componentes de la ventana
        this.getContentPane().revalidate();
        this.getContentPane().repaint();
        
        //  Esto fuerza a Java Swing a actualizar todo el árbol visual
        javax.swing.SwingUtilities.updateComponentTreeUI(this);
    
    }//GEN-LAST:event_MenuItemAltaClientesActionPerformed

    private void MenuItemManteRutinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemManteRutinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemManteRutinasActionPerformed

    private void MenuItemHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemHistorialActionPerformed
                                                         
                                                        
        //  Creamos la instancia de tu panel
        pnHistorial panelHistorial = new pnHistorial();
        
        //  Usamos setBounds para forzar sus dimensiones y posición exacta
        // cojemos el ancho y alto actual del JFrame (la ventana principal)
        panelHistorial.setBounds(0, 0, this.getWidth(), this.getHeight());
        
        // Forzamos que el panel sea visible
        panelHistorial.setVisible(true);
        
        //  Limpiamos el JFrame
        this.getContentPane().removeAll();
        
        //  Aplicamos un layout simple que ocupa toda la pantalla
        this.getContentPane().setLayout(new java.awt.BorderLayout());
        
        //  Añadimos el panel en el centro
        this.getContentPane().add(panelHistorial, java.awt.BorderLayout.CENTER);
        
        //  Refrescamos toda la jerarquía de componentes de la ventana
        this.getContentPane().revalidate();
        this.getContentPane().repaint();
        
        // Opcional: Esto fuerza a Java Swing a actualizar todo el árbol visual
        javax.swing.SwingUtilities.updateComponentTreeUI(this);
    
    
    }//GEN-LAST:event_MenuItemHistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemAltaClientes;
    private javax.swing.JMenuItem MenuItemHistorial;
    private javax.swing.JMenuItem MenuItemManteRutinas;
    private javax.swing.JMenu MenuOperraciones;
    private javax.swing.JMenu MenuSalir;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
