/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Datos.Empresa;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author manu2
 */
public class pnAforo extends javax.swing.JPanel {

   private Empresa empresa;
   public pnAforo(Empresa empresa) {
        initComponents();
        this.empresa = empresa;
        actualizarAforo();
        
        // Configurar tecla ESCAPE
        txtDni.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE) txtDni.setText("");
                if (e.getKeyCode() == KeyEvent.VK_ENTER) btnDentroActionPerformed(null);
            }
        });
    }
   private void actualizarAforo() {
        LabelAforo.setText(String.valueOf(empresa.getCantidadAforoActual()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelAforo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDentro = new javax.swing.JButton();
        btnFuera = new javax.swing.JButton();
        txtDni = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        LabelAforo.setText("Aforo");

        jLabel2.setText("CONTROL DE AFORO");

        btnDentro.setText("checkin");
        btnDentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDentroActionPerformed(evt);
            }
        });

        btnFuera.setText("chekout");
        btnFuera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFueraActionPerformed(evt);
            }
        });

        jLabel1.setText("DNI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(LabelAforo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(22, 22, 22)
                                .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDentro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(btnFuera)
                        .addGap(78, 78, 78))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(LabelAforo)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDentro)
                    .addComponent(btnFuera))
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFueraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFueraActionPerformed
if (empresa.checkOut(txtDni.getText())) {
            JOptionPane.showMessageDialog(this, "Salida registrada");
            actualizarAforo();
            txtDni.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "El DNI no está en el aforo.");
        }
    }//GEN-LAST:event_btnFueraActionPerformed

    private void btnDentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDentroActionPerformed
       if (empresa.checkIn(txtDni.getText())) {
            JOptionPane.showMessageDialog(this, "Entrada registrada");
            actualizarAforo();
            txtDni.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Error. Ya dentro o DNI no existe.");
        }
    }//GEN-LAST:event_btnDentroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelAforo;
    private javax.swing.JButton btnDentro;
    private javax.swing.JButton btnFuera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtDni;
    // End of variables declaration//GEN-END:variables
}
