/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Datos.Cliente;
import Datos.Empresa;
import Datos.Entrenamiento;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class pnHistorial extends javax.swing.JPanel {
    private Empresa empresa;
    private Cliente clienteActual;
   
    //cada vez que metamos un entrenamiento asignamos horas .
    public pnHistorial(Empresa empresa) {
        initComponents();
        this.empresa = empresa;
        configurarTeclado();
        //cargarRutinas();
       
    }
    private void configurarTeclado() {
        txtDni.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    btnVisualizarActionPerformed(null); // Ejecuta el botón de buscar
                } else if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
                    btnCancelarActionPerformed(null); // Limpia todo
                }
            }
        });
    }
    private void actualizarTablaHistorial() {
    // 1. Obtenemos el modelo de la tabla (sustituye jTable1 por el nombre de tu tabla si lo cambiaste)
    DefaultTableModel modelo = (DefaultTableModel) TablaHistorial.getModel();
    
    // 2. Limpiamos la tabla borrando todas las filas anteriores
    modelo.setRowCount(0); 

    // 3. Si hay un cliente seleccionado, rellenamos con sus datos
    if (clienteActual != null) {
        for (Entrenamiento e : clienteActual.getHistorial()) {
            // Creamos un vector (fila) con los datos en el mismo orden que las columnas
            Object[] fila = new Object[5];
            fila[0] = e.getFecha();
            fila[1] = e.getRutina().getNombre();
            fila[2] = e.getPeso() + " kg";
            fila[3] = e.getSeries();
            fila[4] = e.getRepeticiones();
            
            // Añadimos la fila al modelo
            modelo.addRow(fila);
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ScrollHistorial = new javax.swing.JScrollPane();
        TablaHistorial = new javax.swing.JTable();
        txtDni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnVisualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Historial de Entrenamientos ");

        TablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Rutina", "Peso", "Series", "Repeticiones"
            }
        ));
        ScrollHistorial.setViewportView(TablaHistorial);

        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });

        jLabel2.setText("DNI");

        btnVisualizar.setText("Visualizar");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnVisualizar))
                            .addComponent(ScrollHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnVisualizar))
                .addGap(18, 18, 18)
                .addComponent(ScrollHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
      String dni = txtDni.getText().trim();
        clienteActual = empresa.getCliente(dni);

        if (clienteActual != null) {
            actualizarTablaHistorial(); // Llena la tabla
        } else {
            JOptionPane.showMessageDialog(this, "Cliente no encontrado.");
            clienteActual = null;
            actualizarTablaHistorial(); // Deja la tabla vacía
        }
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtDni.setText("");
        clienteActual = null;
        actualizarTablaHistorial(); // Vacía la tabla
        txtDni.requestFocus(); // Vuelve el cursor al buscador
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollHistorial;
    private javax.swing.JTable TablaHistorial;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtDni;
    // End of variables declaration//GEN-END:variables
}
